services:
  db:
    image: postgres:15
    container_name: agency_db_dev
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
