version: "3.8"

services:
  db:
    image: postgres:15
    container_name: agency_db_dev
    # подхватывает переменные из .env.dev, в том числе DATABASE_URL
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agency_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
