version: "3.8"

services:
  db:
    image: postgres:15
    container_name: agency_db_dev
    env_file: .env.dev
    environment:
      # эти переменные нужны Postgres, но дублируются из env_file
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agency_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
