name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Контейнер Postgres, доступный по hostname "db"
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agency_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d agency_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Окружение, видимое во всех шагах
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/agency_test
      ENV: dev
      RAW_DATA_PATH: data/raw/data.csv
      MODEL_SAVE_PATH: models/catboost_model.pkl

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-app.txt
          pip install -r requirements-dev.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h db -p 5432 -U postgres; do
            echo "Waiting for Postgres on localhost:5432..."
            sleep 2
          done

      - name: Initialize database schema
        run: |
          python - <<'PYCODE'
          from src.db.session import init_db
          init_db()
          print("✅ Tables created in agency_test")
          PYCODE

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=src --cov-report=term --cov-report=xml --cov-fail-under=85
