name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agency_test
        # Не пробрасываем порты — внутри runner’а сервис доступен по hostname db
        options: >-
          --health-cmd "pg_isready -U postgres -d agency_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-app.txt
          pip install -r requirements-dev.txt

      - name: Export environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@db:5432/agency_test" >> $GITHUB_ENV
          echo "ENV=dev"                                   >> $GITHUB_ENV
          echo "RAW_DATA_PATH=data/raw/data.csv"           >> $GITHUB_ENV
          echo "MODEL_SAVE_PATH=models/catboost_model.pkl" >> $GITHUB_ENV

      - name: Wait for Postgres to be ready
        run: |
          echo "Sleeping 15s to let Postgres start…"  
          sleep 15

      - name: Initialize DB schema
        run: |
          python - <<'PYCODE'
          from src.db.session import init_db
          init_db()
          print("✅ Tables created in agency_test")
          PYCODE

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=src --cov-report=term --cov-report=xml --cov-fail-under=85
